version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: tester
      MYSQL_DATABASE: octopus
    ports:
      - "3306:3306"
      - "33060:33060"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: