version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: octopus-app:0.17.0
    ports:
      - "80:80"
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: tester
      MYSQL_DATABASE: octopus
    ports:
      - "3306:3306"
      - "33060:33060"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:

volumes:
  mysql-data: